export const centresOfExcellence = [
  "Artificial Intelligence & Machine Learning",
  "Data Science",
  "Drone Technology",
  "Robotics",
  "Self-Driving Cars",
  "Electric Vehicles",
  "Digital Twin & AR/VR",
  "Java Full Stack Development",
  "MERN Stack",
  "Blockchain Technology",
  "Game Development",
  "Mobile App Development",
  "3D Design & Printing",
  "Internet of Things (IoT)",
  "Cloud Computing",
  "Edge Computing",
  "Chip Design",
  "PCB Design & Manufacturing",
  "Fully Automated Surface Mount Technology",
  "ARM Microcontrollers",
  "Renewable Energy",
  "MEMS",
  "Nanotechnology",
];
